version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Patient: The Patient microservice
  ###################################
  patient:
    build:
      context: ./
      dockerfile: patient.Dockerfile
    image: bryanshing/patient:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/patient
      PYTHONUNBUFFERED: 1
    ports:
        - "5000:5000"
 
  #######################################################
  # Clinic: The Clinic microservice
  #######################################################
  clinic:
    build:
      context: ./
      dockerfile: clinic.Dockerfile
    image: bryanshing/clinic:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/clinic
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  #######################################################
  # Appointment: The Appointment microservice
  #######################################################
  appointment:
    build:
      context: ./
      dockerfile: appointment.Dockerfile
    image: bryanshing/appointment:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/appointment
      PYTHONUNBUFFERED: 1
    ports:
        - "5003:5003"

  #######################################################
  # Distance: The Distance microservice
  #######################################################
  distance:
    build:
      context: ./
      dockerfile: distance.Dockerfile
    image: bryanshing/distance:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
        - "5001:5001"

  #######################################################
  # Drug: The Drug microservice
  #######################################################
  drug:
    build:
      context: ./
      dockerfile: drug.Dockerfile
    image: bryanshing/drug:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/drug
      PYTHONUNBUFFERED: 1
    ports:
      - "5007:5007"

  #######################################################
  # PatientRecord: The PatientRecord microservice
  #######################################################
  patientRecord:
    build:
      context: ./
      dockerfile: patientRecord.Dockerfile
    image: bryanshing/patient_record:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/patientRecord
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  #######################################################
  # Subsidy: The Subsidy microservice
  #######################################################
  subsidy:
    build:
      context: ./
      dockerfile: subsidy.Dockerfile
    image: bryanshing/subsidy:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/subsidy
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Notification: The Notification microservice
  #################################################
  notification:
    build:
      context: ./
      dockerfile: notification.Dockerfile
    image: bryanshing/notification:esd
    restart: always
    depends_on:
      - rabbitmq
      - prescribeDrug
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # PrescribeDrug: The PrescribeDrug microservice
  ###############################################
  prescribeDrug:
    build:
      context: ./
      dockerfile: prescribeDrug.Dockerfile
    image: bryanshing/prescribe_drug:esd
    restart: always
    depends_on:
      - clinic
      - patientRecord
      - drug
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      clinic_URL: http://clinic:5002/clinic/
      drug_URL: http://drug:5007/drug/
      patientRecord_URL: http://patientRecord:5007/patientRecord/
      PYTHONUNBUFFERED: 1
    ports:
      - "5120:5120"

  ###############################################
  # ViewClinics: The ViewClinics microservice
  ###############################################
  viewClinics:
    build:
      context: ./
      dockerfile: viewClinics.Dockerfile
    image: bryanshing/view_clinics:esd
    restart: always
    depends_on:
      - clinic
      - distance
      - appointment
      - patient
    environment:
      clinic_URL: http://clinic:5002/clinic
      distance_URL: http://distance:5001/checkDist
      appointment_URL: http://appointment:5003/appointment
      patient_URL: http://patient:5000/patient/
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ###############################################
  # SetAppointment: The SetAppointment microservice
  ###############################################
  setAppointment:
    build:
      context: ./
      dockerfile: setAppointment.Dockerfile
    image: bryanshing/set_appointment:esd
    restart: always
    depends_on:
      - subsidy
      - appointment
      - patient
    environment:
      subsidy_URL: http://subsidy:5001/subsidy/
      appt_URL: http://appointment:5003/set_appointment
      patient_URL: http://patient:5000/patient/
      PYTHONUNBUFFERED: 1
    ports:
      - "5008:5008"